### ISSUE TITLE
Mouse Brain datasets

### ISSUE THREAD

**Issue by zzdj11** [tju-zl/MuCoST#1]
Hello, where can I find the real label file of Mouse Brain datasets? (metadata.tsv)
Looking forward to your reply! Thank you very much!!
Ann_df = pd.read_csv(os.path.join('Data/2-Mouse_Brain_Anterior/', 'metadata.tsv'), sep='\t', header=0, index_col=0)

**Comment by tju-zl** [comment]
Please download the dataset via [https://drive.google.com/drive/folders/1VQfp4IiGSgxyQkM1bzGoN-_M-D5at7op?usp=drive_link](url). I hope this helps! If you have any more questions or need further assistance, feel free to ask.

**Comment by zzdj11** [comment]
Thank you very much for your reply! I am sorry that I can't find the real labels used in the MuCoST_MBH file (metadata.tsv). Could you please help me again? Thank you very much!
![微信截图_20240601203044](https://github.com/tju-zl/MuCoST/assets/69029746/33eb49ef-c9bf-4371-9bcb-dfb60d4490ff)

**Comment by tju-zl** [comment]
The dataset of the figure you mentioned comes from Squidpy (https://squidpy.readthedocs.io/en/stable/notebooks/tutorials/tutorial_visium_hne.html), and the ground truth is defined in adata.obs['cluster']. Unfortunately, the original work dose not provide the 'metadata.tsv' and ground truth in the MBH dataset.

**Comment by zzdj11** [comment]
Thank you so much for taking the time to answer my questions.
